sonar.projectKey=stajproje
sonar.working.directory=C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi
sonar.pullrequest.cache.basepath=C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi

F39C8588-5DE2-4DBD-94CB-0C47FA7D52F0.sonar.projectKey=stajproje:F39C8588-5DE2-4DBD-94CB-0C47FA7D52F0
F39C8588-5DE2-4DBD-94CB-0C47FA7D52F0.sonar.projectName=StajWebProjesi
F39C8588-5DE2-4DBD-94CB-0C47FA7D52F0.sonar.projectBaseDir=C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi
F39C8588-5DE2-4DBD-94CB-0C47FA7D52F0.sonar.sourceEncoding=utf-8
F39C8588-5DE2-4DBD-94CB-0C47FA7D52F0.sonar.tests=
F39C8588-5DE2-4DBD-94CB-0C47FA7D52F0.sonar.sources=\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Controllers\\AccountController.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Controllers\\DatabaseController.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Controllers\\DataController.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Controllers\\HomeController.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Migrations\\20260716054414_InitialCreate.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Migrations\\20260716054414_InitialCreate.Designer.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Migrations\\20260716064835_SqliteInitialCreate.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Migrations\\20260716064835_SqliteInitialCreate.Designer.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Migrations\\AppDbContextModelSnapshot.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Models\\AppDbContext.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Models\\AppDbContextFactory.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Models\\BatchSelectionViewModel.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Models\\ColumnMappingDto.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Models\\DbConnectionInfo.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Models\\ErrorViewModel.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Models\\User.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Program.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\obj\\Debug\\net10.0\\StajWebProjesi.GlobalUsings.g.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\obj\\Debug\\net10.0\\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\obj\\Debug\\net10.0\\StajWebProjesi.AssemblyInfo.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\obj\\Debug\\net10.0\\StajWebProjesi.RazorAssemblyInfo.cs",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\css\\charts.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\css\\login.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\css\\site.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\favicon.ico",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\js\\data-manager.js",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\js\\site.js",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.css.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.min.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.min.css.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.rtl.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.rtl.css.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.rtl.min.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.rtl.min.css.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.css.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.min.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.min.css.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.rtl.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.rtl.css.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.rtl.min.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.rtl.min.css.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.css.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.min.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.min.css.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.rtl.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.rtl.css.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.rtl.min.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.rtl.min.css.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.css.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.min.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.min.css.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.rtl.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.rtl.css.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.rtl.min.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.rtl.min.css.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.bundle.js",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.bundle.js.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.bundle.min.js",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.bundle.min.js.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.esm.js",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.esm.js.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.esm.min.js",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.esm.min.js.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.js",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.js.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.min.js",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.min.js.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\bootstrap\\LICENSE",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\jquery-validation-unobtrusive\\dist\\jquery.validate.unobtrusive.js",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\jquery-validation-unobtrusive\\dist\\jquery.validate.unobtrusive.min.js",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\jquery-validation-unobtrusive\\LICENSE.txt",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\jquery-validation\\dist\\additional-methods.js",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\jquery-validation\\dist\\additional-methods.min.js",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\jquery-validation\\dist\\jquery.validate.js",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\jquery-validation\\dist\\jquery.validate.min.js",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\jquery-validation\\LICENSE.md",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\jquery\\dist\\jquery.js",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\jquery\\dist\\jquery.min.js",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\jquery\\dist\\jquery.min.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\jquery\\dist\\jquery.slim.js",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\jquery\\dist\\jquery.slim.min.js",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\jquery\\dist\\jquery.slim.min.map",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\wwwroot\\lib\\jquery\\LICENSE.txt",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\appsettings.Development.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\appsettings.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Views\\Account\\Login.cshtml",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Views\\Database\\Tables.cshtml",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Views\\Home\\Index.cshtml",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Views\\Shared\\Error.cshtml",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Views\\Shared\\_Layout.cshtml",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Views\\Shared\\_ValidationScriptsPartial.cshtml",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Views\\_ViewImports.cshtml",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Views\\_ViewStart.cshtml",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Views\\Shared\\_Layout.cshtml.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\session_cache.db",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\session_cache.db-shm",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\session_cache.db-wal",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\stajweb.db",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\stajweb.db-shm",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\stajweb.db-wal",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\Properties\\launchSettings.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\obj\\project.assets.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\obj\\StajWebProjesi.csproj.nuget.dgspec.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\bin\\Debug\\net10.0\\StajWebProjesi.deps.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\bin\\Debug\\net10.0\\StajWebProjesi.runtimeconfig.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\bin\\Debug\\net10.0\\StajWebProjesi.staticwebassets.endpoints.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\bin\\Debug\\net10.0\\StajWebProjesi.staticwebassets.runtime.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\obj\\Debug\\net10.0\\rbcswa.dswa.cache.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\obj\\Debug\\net10.0\\rjimswa.dswa.cache.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\obj\\Debug\\net10.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\obj\\Debug\\net10.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\obj\\Debug\\net10.0\\rpswa.dswa.cache.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\obj\\Debug\\net10.0\\StajWebProjesi.sourcelink.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\obj\\Debug\\net10.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\obj\\Debug\\net10.0\\staticwebassets.build.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\obj\\Debug\\net10.0\\staticwebassets.development.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\.git\\cursor\\crepe\\6b7583c3588e057224053087f58cc1bc9a1a409a\\metadata.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\bin\\Debug\\net10.0\\BuildHost-net472\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe.config",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\bin\\Debug\\net10.0\\BuildHost-netcore\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.deps.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\bin\\Debug\\net10.0\\BuildHost-netcore\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\obj\\Debug\\net10.0\\scopedcss\\bundle\\StajWebProjesi.styles.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\obj\\Debug\\net10.0\\scopedcss\\projectbundle\\StajWebProjesi.bundle.scp.css",\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\obj\\Debug\\net10.0\\scopedcss\\Views\\Shared\\_Layout.cshtml.rz.scp.css"

F39C8588-5DE2-4DBD-94CB-0C47FA7D52F0.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\.sonarqube\\out\\0"
F39C8588-5DE2-4DBD-94CB-0C47FA7D52F0.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\.sonarqube\\out\\0\\Issues.json"
F39C8588-5DE2-4DBD-94CB-0C47FA7D52F0.sonar.cs.scanner.telemetry=\
"C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\.sonarqube\\out\\0\\Telemetry.json"

F39C8588-5DE2-4DBD-94CB-0C47FA7D52F0.sonar.working.directory=C:\\Users\\omer\\Desktop\\staj proje\\StajWebProjesi\\.sonarqube\\out\\.sonar\\mod0
sonar.organization=omerfarukk5556-code
sonar.visualstudio.enable=false
sonar.host.url=https://sonarcloud.io

sonar.modules=F39C8588-5DE2-4DBD-94CB-0C47FA7D52F0

